completed javascript-loops-practice - Bryan Brown
bbrown949/c0323-code-solutions pull request #11
Opened 2023-03-24 03:03 UTC by bbrown949

<img width="602" alt="Screenshot 2023-03-23 at 7 57 57 PM" src="https://user-images.githubusercontent.com/117103446/227413675-d46f567b-8206-4702-bc95-c4d627cf467b.png">
<img width="909" alt="Screenshot 2023-03-23 at 7 57 47 PM" src="https://user-images.githubusercontent.com/117103446/227413679-4897c274-0b92-493b-8c05-3a67229bdcd6.png">
<img width="674" alt="Screenshot 2023-03-23 at 7 58 03 PM" src="https://user-images.githubusercontent.com/117103446/227413685-b3d2b01f-0ee5-42d3-be4a-c0871809f1f3.png">

2023-03-24 16:28 UTC, shawnkost requested changes
Couple small changes requested here Bryan!

2023-03-24 16:28 UTC, shawnkost commented on javascript-loops-practice/countdown.js
> +    console.log(currentNumber);
Delete any unused console logs! These are purely for debugging / testing purposes.

2023-03-24 16:28 UTC, shawnkost commented on javascript-loops-practice/odd-or-even.js
> +    } else output.push('odd');
You should have another `{` after `else`. 

```
} else {
```

2023-03-24 23:04 UTC, bbrown949 commented on javascript-loops-practice/odd-or-even.js
> +    } else output.push('odd');
i tried that and it broke the code...

I removed the console log and and will push again for you to take a look

2023-03-27 15:06 UTC, shawnkost requested changes
One more change requested! I added a comment to our previous comment thread

2023-03-27 15:06 UTC, shawnkost commented on javascript-loops-practice/odd-or-even.js
> +    } else output.push('odd');
Did you add another bracket after the else statement? The whole code should look like this
```
function oddOrEven(numbers) {
  const output = [];
  for (let i = 0; i < numbers.length; i++) {
    if (numbers[i] % 2 === 0) {
      output.push('even');
    } else {
      output.push('odd');
    }
  } 
  return output;
}
```

2023-03-27 15:10 UTC, bbrown949 commented
fixed 👍🏼

2023-03-27 15:11 UTC, shawnkost approved these changes
👍🏻

2023-03-27 15:11 UTC, merged