html-forms - Bryan Brown
bbrown949/c0323-code-solutions pull request #26
Opened 2023-03-29 17:44 UTC by bbrown949

![Screenshot 2023-03-29 at 10 43 44 AM](https://user-images.githubusercontent.com/117103446/228623538-5f1ac3c0-4e16-4135-ab6b-40a133866d1e.png)

2023-03-29 21:54 UTC, shawnkost requested changes
One change requested here Bryan!

2023-03-29 21:54 UTC, shawnkost commented on html-forms/index.html
> +    <label for="email-address">Email</label>
You're missing a `form` element! Everything from line 10 down should be wrapped inside a `form` element

2023-03-31 17:24 UTC, bbrown949 commented on html-forms/index.html
> +    <label for="email-address">Email</label>
fixed!

2023-03-31 17:26 UTC, shawnkost approved these changes
👍🏻

2023-03-31 17:26 UTC, merged