completed css-two-column-layout - Bryan Brown
bbrown949/c0323-code-solutions pull request #34
Opened 2023-04-02 22:57 UTC by bbrown949

![Screenshot 2023-04-02 at 3 52 45 PM](https://user-images.githubusercontent.com/117103446/229383605-d764e5cf-31fd-40a6-b034-3c1c24b0f328.png)

2023-04-04 15:40 UTC, shawnkost requested changes
Just one change here Bryan!

2023-04-04 15:40 UTC, shawnkost commented on css-two-column-layout/styles.css
> +  flex-basis: 50%;
I don't believe this is doing anything. `flex-basis` is a child property, so you'd only apply it to flex items, not a flex parent. So you'd apply it to the columns.

2023-04-07 21:53 UTC, bbrown949 commented on css-two-column-layout/styles.css
> +  flex-basis: 50%;
updated.

2023-04-07 21:54 UTC, shawnkost approved these changes
👍🏻

2023-04-07 21:54 UTC, merged