javascript-forms - Bryan Brown
bbrown949/c0323-code-solutions pull request #40
Opened 2023-04-05 20:29 UTC by bbrown949

![Screenshot 2023-04-05 at 12 26 22 PM](https://user-images.githubusercontent.com/117103446/230203468-c67087a2-f15e-4df8-a3ad-7e05603d508e.png)

2023-04-05 20:34 UTC, bbrown949 commented
forgot 1st screenshot

<img width="1404" alt="Screenshot 2023-04-05 at 1 33 15 PM" src="https://user-images.githubusercontent.com/117103446/230204772-0e760923-c73b-4418-ab2f-ff1564f72557.png">

2023-04-05 22:57 UTC, shawnkost requested changes
A change requested here Bryan!

2023-04-05 22:57 UTC, shawnkost commented on javascript-forms/form-events.js
> +$userMessage.addEventListener('input', handleInput);
You're missing 6 more event listeners. Each form input should have 3 event listeners, for each event.

2023-04-07 21:58 UTC, bbrown949 commented on javascript-forms/form-events.js
> +$userMessage.addEventListener('input', handleInput);
Updated

2023-04-10 15:52 UTC, shawnkost approved these changes
👍🏻

2023-04-10 16:31 UTC, merged