completed dom-event-delegation exercise - Bryan Brown
bbrown949/c0323-code-solutions pull request #42
Opened 2023-04-06 18:58 UTC by bbrown949

![Screenshot 2023-04-06 at 11 57 15 AM](https://user-images.githubusercontent.com/117103446/230470276-f72e64fb-6063-43ea-8520-867c56463761.png)

2023-04-06 20:42 UTC, shawnkost requested changes
One change here Bryan!

2023-04-06 20:42 UTC, shawnkost commented on dom-event-delegation/main.js
> +    return $closest;
Remove this, we don't want to return anything here.

2023-04-07 17:15 UTC, bbrown949 commented on dom-event-delegation/main.js
> +    return $closest;
removed.

2023-04-07 17:15 UTC, shawnkost approved these changes
👍🏻

2023-04-07 17:15 UTC, merged