completed javascript-loops exercise
bbrown949/c0323-code-solutions pull request #9
Opened 2023-03-23 04:30 UTC by bbrown949

<img width="1167" alt="Screenshot 2023-03-22 at 9 30 09 PM" src="https://user-images.githubusercontent.com/117103446/227103551-e3b0c587-67a0-4b15-bb36-71470e2f7c9f.png">

2023-03-23 04:31 UTC, bbrown949 commented
better screenshot
<img width="1165" alt="Screenshot 2023-03-22 at 9 31 20 PM" src="https://user-images.githubusercontent.com/117103446/227103696-f78905ee-3b2f-49a0-befc-81b1a3da8dc7.png">

2023-03-23 18:42 UTC, shawnkost requested changes
Some changes requested here Bryan!! You still haven't submitted `javascript-conditonals`, so you'll need to make sure to also submit the `javascript-conditionals` code on that branch as well, so the exercise will get marked as complete. You can just download the starter files again, and copy all the current work you have, and paste it there.

2023-03-23 18:42 UTC, shawnkost commented on javascript-conditionals/main.js
> +  else console.log(false);
You're missing brackets (`{}`) after your `if` & `else` statements

2023-03-23 18:42 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH > 0) {
This should also be checking if it's less than 7

2023-03-23 18:42 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH <= 14) {
This should also be checking if it's greater than 7

2023-03-23 18:42 UTC, shawnkost commented on javascript-loops/main.js
> +
You're missing a function! You should have a function `doubleAll`

2023-03-26 19:35 UTC, bbrown949 commented
Added doubleAll function on javascript-loops
<img width="690" alt="Screenshot 2023-03-26 at 12 33 40 PM" src="https://user-images.githubusercontent.com/117103446/227799963-7175641b-d391-43a3-9c1b-bc63b6918abb.png">

2023-03-27 15:03 UTC, shawnkost approved these changes
👍🏻

2023-05-09 22:24 UTC, merged